/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge.ConversorDeMoeda;

import model.UsdBrl;
import view.MainScreen;

public class App {

    public static void main(String[] args) throws Exception{
        
                System.out.println(UsdBrl.valorDolarDouble());

                MainScreen tela = new MainScreen();
                tela.setVisible(true);
    }

    
}
