/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge.ConversorDeMoeda;

import model.DolarPrice;

public class App {

    public static void main(String[] args) throws Exception{
        
                System.out.println(DolarPrice.valorDolarDouble());
        
    }
}
