/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge.ConversorDeMoeda;

import model.UsdBrl;
import view.MainScreen;
import view.MainScreen2;

public class App {

    public static void main(String[] args) throws Exception{
        
                //System.out.println(UsdBrl.valorDolarDouble());

                MainScreen2 tela = new MainScreen2();
                tela.setVisible(true);
    }

    
}
